# Generated by Django 5.0.3 on 2024-03-05 15:19

import events.enums
import lib.bit_enum_list_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('days', lib.bit_enum_list_field.BitEnumListField(events.enums.Weekdays)),
            ],
        ),
    ]
